export const SET_USER = 'SET_USER';
export const SET_GAMES = 'SET_GAMES';
export const SET_KING_GAME = 'SET_KING_GAME';
export const SET_RANKS = 'SET_RANKS';
export const SET_CURRENT_GAME = 'SET_CURRENT_GAME';
export const SET_CURRENT_GAME_CODE = 'SET_CURRENT_GAME_CODE';
export const DUMMY = 'DUMMY';
export const UPDATE_GAME = 'UPDATE_GAME';
export const SET_TEAMS = 'SET_TEAMS';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const SET_LIVE_STREAM_URL = 'SET_LIVE_STREAM_URL';

export const ECHO_GAME_CHANGED = 'ECHO_GAME_CHANGED';
export const ECHO_GAME_COUNT_CHANGED = 'ECHO_GAME_COUNT_CHANGED';
export const SET_STAT = 'SET_STAT';

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';

export const SET_CURRENT_SHOW_RESULTS_IMG = 'SET_CURRENT_SHOW_RESULTS_IMG';
